Repository witseie-elen4010/2025-group-lab-001, pull requests merged in 2025-05, with the labels that each got.

#8 Game creation
  .gitignore
  package-lock.json
  package.json
  src/app.js
  src/config/express.js
  src/config/gameConstants.js
  src/models/Game.js
  src/models/Player.js
  src/public/js/getAllPlayers.js
  src/routes/gaming.js
  src/routes/index.js
  src/views/error.html
  src/views/gameError.html
  src/views/index.html
  src/views/wait.html
  tests/models/Game.test.js
  tests/models/Player.test.js
  tests/routes/gaming.test.js
Labels: user-story

#11 Voting out a player
  package.json
  src/controllers/votingFunctions.js
  src/models/Game.js
  src/models/Player.js
  src/public/js/vote.js
  src/routes/gaming.js
  src/views/finished.html
  src/views/vote.html
  src/views/waitingForVotes.html
  tests/models/Vote.test.js
Labels: user-story

#9 Join Game
  src/config/express.js
  src/config/gameConstants.js
  src/public/js/getRole.js
  src/public/js/startGame.js
  src/routes/gaming.js
  src/routes/index.js
  src/views/index.html
  src/views/join.html
  src/views/wait.html
  tests/routes/gaming.test.js
Labels: user-story

#13 fix: update Jest moduleNameMapper to include controllers- Add @contro…
  package.json
  src/routes/gaming.js
Labels: bug

#14 Chat room
  src/app.js
  src/public/js/chatLog.js
  src/routes/gaming.js
  src/routes/index.js
  src/views/chatRoom.html
  tests/routes/gaming.test.js
Labels: user-story

#10 Word share
  package-lock.json
  package.json
  src/app.js
  src/models/Dictionary.js
  src/models/Game.js
  src/models/Player.js
  src/public/js/shareDescription.js
  src/public/js/shareWord.js
  src/routes/gaming.js
  src/routes/index.js
  src/views/wordShare.html
  tests/models/Game.test.js
  tests/models/Player.test.js
  tests/routes/gaming.test.js
Labels: user-story

#25 feat: integrate chat and word sharing features
  src/app.js
  src/config/express.js
  src/controllers/votingFunctions.js
  src/models/Game.js
  src/models/Player.js
  src/public/js/chatLog.js
  src/public/js/shareWord.js
  src/public/js/startGame.js
  src/routes/gaming.js
  src/routes/index.js
  src/views/chatRoom.html
  src/views/wordShare.html
  tests/models/Game.test.js
  tests/models/Vote.test.js
  tests/routes/gaming.test.js
Labels: epic

#26 fix: ensure voting is functioning for all players
  src/config/express.js
  src/controllers/votingFunctions.js
  src/public/js/vote.js
  src/public/js/voteWaiting.js
  src/routes/gaming.js
  src/views/waitingForVotes.html
  tests/models/Vote.test.js
Labels: bug

#27 fix: add better routing system
  src/config/express.js
  src/routes/home.js
  src/routes/index.js
Labels: developer-sized-story

#28 Check logs
  package.json
  src/app.js
  src/config/express.js
  src/middleware/requestLogger.js
  src/public/js/admin.js
  src/public/js/getAllPlayers.js
  src/routes/admin.js
  src/views/admin.html
  src/views/wait.html
  tests/middleware/requestLogger.test.js
  tests/routes/admin.test.js
Labels: user-story

#30 Create account
  package-lock.json
  package.json
  src/config/express.js
  src/controllers/accountFunctions.js
  src/public/js/accounts.js
  src/routes/account.js
  src/views/accounts.html
  src/views/createAccount.html
  src/views/error.html
  src/views/gameError.html
  src/views/index.html
  src/views/join.html
  tests/models/Account.test.js
  tests/routes/gaming.test.js
Labels: user-story

#41 chore: adjust home page
  src/routes/home.js
  src/views/createGame.html
  src/views/index.html
  src/views/leaderboard.ejs
Labels: developer-sized-story

#42 Improve security
  package-lock.json
  package.json
  src/app.js
  src/controllers/accountFunctions.js
  src/controllers/votingFunctions.js
  src/middleware/auth.js
  src/public/js/chatLog.js
  src/public/js/getRole.js
  src/public/js/shareDescription.js
  src/public/js/shareWord.js
  src/public/js/startGame.js
  src/public/js/vote.js
  src/public/js/voteWaiting.js
  src/routes/account.js
  src/routes/gaming.js
  src/routes/home.js
  src/views/accounts.html
  src/views/chatRoom.html
  src/views/createGame.html
  src/views/join.html
  src/views/vote.html
  src/views/wait.html
  src/views/waitingForVotes.html
  src/views/wordShare.html
  tests/middleware/auth.test.js
  tests/models/Account.test.js
  tests/models/lobbies.test.js
  tests/routes/gaming.test.js
Labels: security, user-story

#44 Improve logging
  src/config/gameConstants.js
  src/middleware/formatters.js
  src/middleware/requestLogger.js
  src/public/js/admin.js
  src/views/admin.html
  tests/middleware/formatters.test.js
  tests/middleware/requestLogger.test.js
  tests/routes/admin.test.js
Labels: enhancement, user-story

#43 Password recovery
  package-lock.json
  package.json
  src/controllers/accountFunctions.js
  src/routes/account.js
  src/views/forgotPassword.html
  src/views/login.html
  src/views/passwordReset.html
  src/views/resetPassword.html
  src/views/verifyOTP.html
  tests/models/Account.test.js
Labels: user-story

#46 test: add error handling tests for routes
  tests/routes/account.test.js
  tests/routes/gaming.test.js
  tests/routes/home.test.js
  tests/routes/index.test.js
Labels: documentation

#54 Prompts vs Wordlsits
  .DS_Store
  src/models/Dictionary.js
  src/models/Game.js
  src/routes/home.js
  src/views/createGame.html
  src/views/wordShare.html
  tests/models/Game.test.js
Labels: enhancement, user-story

#52 chore: changed form to radio buttons for voting
  src/public/js/vote.js
  src/routes/gaming.js
  src/views/vote.html
  tests/routes/gaming.test.js
Labels: developer-sized-story

#48 Guest mode
  src/controllers/accountFunctions.js
  src/middleware/auth.js
  src/routes/home.js
  tests/routes/gaming.test.js
Labels: user-story

#60 feat: added a simple admin login button so users can find the logs wi…
  src/controllers/adminFunctions.js
  src/public/js/accounts.js
  src/routes/admin.js
  src/views/createAccount.html
  src/views/login.html
Labels: enhancement

#61 Game Timing
  src/config/express.js
  src/models/Game.js
  src/public/js/chatLog.js
  src/public/js/shareDescription.js
  src/public/js/startGame.js
  src/public/js/vote.js
  src/routes/gaming.js
  src/routes/home.js
  src/views/chatRoom.html
  src/views/createGame.html
  src/views/wordShare.html
Labels: enhancement, user-story

#68 chore: add page to display voted out player
  src/public/js/voteResults.js
  src/public/js/voteWaiting.js
  src/routes/gaming.js
  src/views/voteResults.html
Labels: developer-sized-story
